### ISSUE TITLE
Release 0.1.0 version?

### ISSUE THREAD

**Issue by rwjblue** [sreedhar7/ember-app-scheduler#7]
There are a few reasons for this bump:

* It allows consumers to depend on ember-app-scheduler via `^` (caret) dependency. Which means they can automatically get patch version bumps if we have bugs that need fixing.
* It signifies that a breaking change has occurred (talking about dropping support for Node < 4 in my last PR).

Any objections?

**Comment by sreedhar7** [comment]
Done and published 0.1.0 to npm.

**Comment by rwjblue** [comment]
Thank you!
