### ISSUE TITLE
Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-app-scheduler`'s `package.json`

### ISSUE THREAD

**Issue by briangonzalez** [sreedhar7/ember-app-scheduler#9]
Seeing this in my project which uses ember-app-scheduler.

**Comment by rwjblue** [comment]
ember-app-scheduler@0.1.0 has the correct dependencies set, can you confirm that you are using the latest version?

**Comment by briangonzalez** [comment]
Looks like we're using an older version by way of https://github.com/dollarshaveclub/ember-router-scroll/blob/master/package.json, whoops!

Thank you 🙏
